In [1]:
import numpy as np #numpy 모듈을 np라는 이름으로 가져오는 것 

In [4]:
#일차원 배열과 이차원 배열 생성
li = list(range(1, 10)) #일차원 list 생성
print(li)

#list를 이용해서 ndarray 생성
ar = np.array(li)
print(ar)

#일차원 배열을 생성한 후 행과 열의 개수를 3 X 3 으로 변경
matrix = np.array(li).reshape((3, 3)) 
print(matrix)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
#인덱싱 - 데이터 1개 가져오기
data1 = ar[0]
print(data1)

#이차원 배열에서 데이터 1개 찾아오기
data2 = matrix[0, 0]
data3 = matrix[0][0]
print(data2)
print(data3)

#이차원 배열에서 행 하나 찾아오기
row = matrix[0,:] #matrix[0][:], matrix[0]
print(row)

#이차원 배열에서 열 하나 찾아오기
column = matrix[:, 0]
print(column)

1
1
1
[1 2 3]
[1 4 7]


In [9]:
#일반 인덱싱한 데이터는 파이썬의 기본 데이터와 동일하게 동작을 합니다.
#파이썬의 scala data는 일반적으로 immutable (변경 불가능함)
#scala data는 다른 변수에 대입할 때 값을 복사해서 대입합니다.

a = 10
b = a #b = 10
b = 20
print(a)

#파이썬의 vector data는 다른 변수에 대입할 때 참조를 복사해서 대입합니다.
ax = [1, 2, 3]
bx = ax #bx = [1, 2, 3]의 참조
bx[0] = 100
print(ax)

10
[100, 2, 3]


In [18]:
#scala data를 복사하는 경우는 원본의 값을 복사해서 대입하기 때문에
#서로 간에 영향을 주지 않습니다.
data1 = 1000
print(data1)
print(ar)

data2 = 1000
print(data2)
print(matrix)

#row는 scala data(primitive type)가 아니고 vector data(non-primitive type)
#vector 데이터를 다른 곳에 대입하면 참조가 복사됩니다.
#복사본을 수정하면 원본도 영향을 받습니다.
row[0] = 1004
print(row)
print(matrix)

#데이터 복제는 copy() 메서드
clone = matrix.copy()
clone[0][0] = 42 #복사본의 데이터를 수정해도 원본에서는 그대로 1004
print(matrix)

1000
[1 2 3 4 5 6 7 8 9]
1000
[[1004    2    3]
 [   4    5    6]
 [   7    8    9]]
[1004    2    3]
[[1004    2    3]
 [   4    5    6]
 [   7    8    9]]
[[1004    2    3]
 [   4    5    6]
 [   7    8    9]]


In [16]:
#파이썬에서의 데이터 복제
#copy 모듈의 copy(shallow copy - 얕은 복사)와 deepcopy(깊은 복사) 함수 이용
#얕은 복사는 한 번은 복제를 하지만 재귀적으로 수행하지 않음
#깊은 복사는 재귀적으로 복제를 수행

import copy
li = [1, 2, 3]
c = li.copy() #얕은 복사
c[0] = 100 #일차원 list의 경우는 원본에 영향을 주지 않음
print(li)

m = [[1, 2, 3], [4, 5, 6]]
c = m.copy() #얕은 복사는 이차원 배열의 경우는 원본에 영향을 줌
m[0][0] = 100
print(m)

d = copy.deepcopy(m) #copy.deepcopy는 재귀적으로 복제를 수행하기 때문에
#복사본의 데이터를 수정해도 원본에는 영향이 없습니다.
print(d)
d[0][0] = 1004
print(m)

[1, 2, 3]
[[100, 2, 3], [4, 5, 6]]
[[100, 2, 3], [4, 5, 6]]
[[100, 2, 3], [4, 5, 6]]


# 슬라이싱

In [20]:
li = [1, 2, 3, 4, 5]
c = li[0:3] #list의 슬라이싱: 얕은 복사 수행
#c와 li는 앞 3개의 데이터가 동일하지만 다른 공간의 데이터
print(c)
c[0] = 100 #c의 값을 변경해도 li에는 영향이 없음
print(li)

ar = np.array(li)
d = ar[0:3] #배열에서 0번째부터 2번째까지 데이터를 복사
#0번째부터 2번째까지 이므로 이 데이터는 3개(vector data)
#참조가 복사

print(d)
d[0] = 100 #d의 값을 수정하면 원본에 영향을 주게 됩니다.
print(ar)

[1, 2, 3]
[1, 2, 3, 4, 5]
[1 2 3]
[100   2   3   4   5]


# Fancy Indexing

In [22]:
#인덱싱을 할 때 list를 이용하는 것
ar = np.array([100, 200, 300, 400, 500])
print(ar[[0, 2]])

[100 300]


In [24]:
print(bool([]))
print(bool([1,2,3]))
print([1,2,3] > 2)

False
True


TypeError: '>' not supported between instances of 'list' and 'int'

In [28]:
#불리언 색인: array의 인덱스에 bool 배열을 대입해서 True인 데이터만 골라내기
ar = np.array([1, 2, 3, 4, 5 ,6, 7])
result = ar[[True, True, False, False, True, False, True]]
print(result)

br = np.array([100, 20, 30, 40 , 50 , 80, 90])
result = ar[(br >= 70) & (br <= 90)]
print(result)

[1 2 5 7]
[6 7]


##ndarray의 연산

In [33]:
#산술 연산
ar = np.array([1, 2, 3, 4, 5])
br = np.array([10, 20, 30, 40, 50])

result = ar + br
print(result)

result = ar + 4 #2개의 차원이 다른 경우로 이 경우 적은 차원의 데이터를 큰 차원으로 수정
#ar + [4, 4, 4, 4, 4]
print(result)

k = range(1, 11)
#일차원 배열을 2행 5열로 수정해서 연산을 수행
cr = np.array(k).reshape((2,5))
print(ar + cr)

[11 22 33 44 55]
[5 6 7 8 9]
[[ 2  4  6  8 10]
 [ 7  9 11 13 15]]


In [37]:
#논리 연산
ar = np.array([1, 2, 3, 4, 5])
br = np.array([10, 20, False, 40, 0])

ar += br

print(1 in ar)
print([1, 2] in ar)
print([1, 100] in ar)

False
False
False


/var/folders/bq/22f7j5dn6x5dcpn8t77q8t4h0000gn/T/ipykernel_23858/853332499.py:8: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  print([1, 2] in ar)
/var/folders/bq/22f7j5dn6x5dcpn8t77q8t4h0000gn/T/ipykernel_23858/853332499.py:9: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  print([1, 100] in ar)


In [40]:
#벡터화된 함수 적용
#매개변수에 100을 더해서 리턴하는 함수

def f(i):
    return i + 100

#벡터화된 함수로 수정
vector_f = np.vectorize(f)
#배열에 벡터화된 함수 적용
print(vector_f(ar))

#람다 함수를 이용해서 동일한 작업 수행
print(np.vectorize(lambda i:i+100)(ar))


[111 122 103 144 105]
[111 122 103 144 105]


In [43]:
matrix = np.array(range(1, 11)).reshape((5, 2))
print(matrix)
print(matrix.reshape((2, 5))) #행과 열의 수를 변경해서 전치
print(matrix.T) #행과 열을 변경
print(np.transpose(matrix)) #행과 열을 변경

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]
[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


In [51]:
np.random.seed(seed=42) #seed 고정
cards = np.array(range(1, 49)) #1부터 48까지의 일차원 배열
print(cards)
#배열을 섞어서 리턴
result = np.random.permutation(cards)
print(result)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
[28 41 27 44 25 38 13 20  5 26  9  4  7 40 34 14 18 46 16 10 17 30 33 47
  1 32 31  6 12 35  2 45 22  3 37 36 24 42 11 23 19 48 21  8 43 15 29 39]


In [63]:
#기본 통계 함수
matrix = np.random.randn(20).reshape((4, 5))
print(matrix)
print(matrix.sum())
print(matrix.std()) #표준 편차
print(matrix.std(ddof=1)) #표준 편차 - 자유도 1 적용
print(np.percentile(matrix, 75)) #75%에 해당하는 값
#행 단위와 열 단위 합계
print(matrix.sum(axis=0)) #열 단위
print(matrix.sum(axis=1)) #행 단위
print(matrix.sum(axis=1, keepdims=True)) #행 단위 - matrix와 동일한 차원으로 리턴

print(matrix.argmax(axis=1))
print(matrix.prod(axis=0))

[[-0.89633518 -0.11198782  1.46894129 -1.12389833  0.9500054 ]
 [ 1.72651647  0.45788508 -1.68428738  0.32684522 -0.08111895]
 [ 0.46779475  0.73612235 -0.77970188 -0.84389636 -0.15053386]
 [-0.96555767  0.15048908 -0.11342125  2.63352822 -1.02509089]]
1.1422982711234242
1.0552836504869048
1.0826981807089602
0.5348766526146782
[ 0.33241837  1.23250869 -1.10846922  0.99257875 -0.30673831]
[ 0.28672534  0.74584044 -0.570215    0.67994749]
[[ 0.28672534]
 [ 0.74584044]
 [-0.570215  ]
 [ 0.67994749]]
[2 0 1 3]
[ 0.69899607 -0.00568044 -0.21879815  0.81638734 -0.01189173]


In [65]:
help(np.sort)

Help on function sort in module numpy:

sort(a, axis=-1, kind=None, order=None)
    Return a sorted copy of an array.
    
    Parameters
    ----------
    a : array_like
        Array to be sorted.
    axis : int or None, optional
        Axis along which to sort. If None, the array is flattened before
        sorting. The default is -1, which sorts along the last axis.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
        and 'mergesort' use timsort or radix sort under the covers and, in general,
        the actual implementation will vary with data type. The 'mergesort' option
        is retained for backwards compatibility.
    
        .. versionchanged:: 1.15.0.
           The 'stable' option was added.
    
    order : str or list of str, optional
        When `a` is an array with fields defined, this argument specifies
        which fields to compare first, second, etc.  A si

In [67]:
#일차원 배열의 정렬
ar = np.array([20, 30, 10, 25, 27])
result = np.sort(ar) #데이터를 정렬
print(result)
print(ar)

#2차원 배열에서 행에서의 정렬
br = np.array([[10, 60, 80], [20, 50, 30], [15, 32, 29]])
result = np.sort(br, axis = 1)
print(result)

[10 20 25 27 30]
[20 30 10 25 27]
[[10 60 80]
 [20 30 50]
 [15 29 32]]


In [82]:
x = range(1, 51)
#위의 데이터를 가지고 10행 5열 짜리 이차원 배열 생성
matrix = np.array(x).reshape((10, 5))
print(matrix)

#행과 열의 개수 가져오기
print(matrix.shape)
print(type(matrix.shape))

cnt = matrix.shape[0]
print(cnt)

#데이터를 가지고 7:3 분할 ... np.split 사용
#여기에 permutation을 적용하면 샘플링 해주는 함수가 됩니다.
k = np.split(matrix, [int(cnt * 0.7), int(cnt * 0.9)])

print(k[0])
print(k[1])
print(k[2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]
(10, 5)
<class 'tuple'>
10
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]
[[36 37 38 39 40]
 [41 42 43 44 45]]
[[46 47 48 49 50]]
